services:
  - type: web
    name: ru-backend
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 1x
      memory: 2048
      storage: 512
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: RU-Backend
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: RENDER_EXTERNAL_URL
        value: "https://ru-backend.onrender.com"
      - key: DJANGO_SUPERUSER_USERNAME
        value: sachin  # Change this
      - key: DJANGO_SUPERUSER_EMAIL
        value: ghoshsachin2301@gmail.com  # Change this
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true  # This will generate a secure random password
    healthCheckPath: /admin/
    autoDeploy: false

databases:
  - name: RU-Backend
    databaseName: ru_backend
    user: ru_backend_user
    plan: free