# Generated by Django 5.1.5 on 2025-01-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_when_missing', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('complexion', models.CharField(max_length=50)),
                ('identifying_marks', models.TextField(blank=True)),
                ('physical_attributes', models.JSONField(default=dict)),
                ('recent_photo', models.ImageField(upload_to='missing_persons/photos/')),
                ('additional_photos', models.JSONField(default=list)),
                ('facial_encoding', models.JSONField(null=True)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_date', models.DateTimeField()),
                ('last_seen_details', models.TextField()),
                ('last_seen_wearing', models.TextField()),
                ('possible_locations', models.JSONField(default=list)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('fir_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Case Resolved')], default='MISSING', max_length=20)),
                ('priority_level', models.IntegerField(default=1)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=100)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cases', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('POLICE_REPORT', 'Police Report'), ('MEDICAL_RECORD', 'Medical Record'), ('ID_PROOF', 'Identity Proof'), ('OTHER', 'Other Document')], max_length=20)),
                ('document', models.FileField(upload_to='missing_persons/documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='missing_persons.missingperson')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
