# Generated by Django 5.1.5 on 2025-01-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_familygroup_familymember_user_families'),
        ('missing_persons', '0002_missingperson_family_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember'),
        ),
    ]
