# Generated by Django 5.1.5 on 2025-01-29 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0003_missingperson_family_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='aadhaar_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='facial_match_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score from facial recognition'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='is_registered_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_known_location',
            field=models.JSONField(default=dict, help_text='Store location history with timestamps'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reporter_type',
            field=models.CharField(choices=[('SELF', 'Self Reported'), ('FAMILY', 'Family Member'), ('POLICE', 'Police Officer'), ('NGO', 'NGO Worker'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
