# Generated by Django 5.1.5 on 2025-01-29 17:32

import missing_persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0005_remove_missingpersondocument_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingpersondocument',
            name='document',
        ),
        migrations.AddField(
            model_name='missingpersondocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=missing_persons.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='recent_photo',
            field=models.ImageField(blank=True, null=True, upload_to=missing_persons.models.photo_upload_path),
        ),
    ]
