# Generated by Django 5.1.5 on 2025-01-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0006_remove_missingpersondocument_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_photos'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_known_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_known_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found'), ('INVESTIGATING', 'Under Investigation'), ('CLOSED', 'Case Closed')], default='MISSING', max_length=20),
        ),
    ]
