# Generated by Django 5.1.5 on 2025-01-29 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_familygroup_familymember_user_families'),
        ('missing_persons', '0007_missingperson_aadhaar_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_persons', to='accounts.familygroup'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
