# Generated by Django 5.1.5 on 2025-03-18 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0008_alter_missingperson_family_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ngo_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
