# Generated by Django 5.1.5 on 2025-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0009_missingperson_assigned_ngo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age_when_missing',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='complexion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='physical_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg'),
        ),
    ]
