# Generated by Django 5.1.5 on 2025-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0010_alter_missingperson_age_when_missing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='age_when_missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='complexion',
            field=models.CharField(choices=[('FAIR', 'Fair'), ('MEDIUM', 'Medium'), ('DARK', 'Dark'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='UNKNOWN', max_length=10),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
