# Generated by Django 5.1.5 on 2025-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0011_alter_missingperson_age_when_missing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=10),
        ),
    ]
