# Generated by Django 5.1.5 on 2025-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaarprofile',
            name='aadhaar_id',
        ),
        migrations.RemoveField(
            model_name='aadhaarprofile',
            name='facial_features',
        ),
        migrations.RemoveField(
            model_name='aadhaarprofile',
            name='iris_scan_hash',
        ),
        migrations.AddField(
            model_name='aadhaarprofile',
            name='aadhaar_number_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aadhaarprofile',
            name='blockchain_reference',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aadhaarprofile',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='aadhaarprofile',
            name='facial_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aadhaarprofile',
            name='fingerprint_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
