# Generated by Django 5.1.5 on 2025-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_familygroup_familymember_user_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text="e.g., {'push': True, 'email': False, 'sms': True}"),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', help_text="e.g., 'en', 'hi', 'ta'", max_length=10),
        ),
    ]
