# Generated by Django 5.1.5 on 2025-03-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_organization_latitude_and_more'),
        ('missing_persons', '0009_missingperson_assigned_ngo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaborations', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_collaborations', to=settings.AUTH_USER_MODEL)),
                ('missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_persons.missingperson')),
            ],
            options={
                'unique_together': {('initiator', 'collaborator', 'missing_person')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='collaboration_files/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.collaboration')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
