# Generated by Django 5.1.5 on 2025-03-19 10:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_collaboration_collaborationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.document_upload_path),
        ),
    ]
