# Generated by Django 5.1.5 on 2025-01-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missing_persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_details', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('wearing', models.TextField(blank=True)),
                ('accompanied_by', models.TextField(blank=True)),
                ('direction_headed', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sightings/photos/')),
                ('additional_photos', models.JSONField(default=list)),
                ('video', models.FileField(blank=True, null=True, upload_to='sightings/videos/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('INVESTIGATING', 'Under Investigation')], default='PENDING', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High Confidence'), ('MEDIUM', 'Medium Confidence'), ('LOW', 'Low Confidence')], default='MEDIUM', max_length=10)),
                ('facial_match_confidence', models.FloatField(blank=True, null=True)),
                ('ml_analysis_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.JSONField(default=dict)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missing_persons.missingperson')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_sightings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sightings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
