# Generated by Django 5.1.5 on 2025-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
