# Generated by Django 5.1.5 on 2025-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sighting_reporter_contact_sighting_reporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='companions',
            field=models.CharField(choices=[('ALONE', 'Alone'), ('WITH_ADULT', 'With Adult'), ('WITH_CHILDREN', 'With Children'), ('WITH_GROUP', 'With Group'), ('UNSURE', 'Unsure')], default='UNSURE', max_length=20),
        ),
        migrations.AddField(
            model_name='sighting',
            name='confidence_level_numeric',
            field=models.FloatField(default=0.0, help_text='Confidence level 0-100'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='crowd_density',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='sighting',
            name='location_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('PUBLIC', 'Public Transport'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='sighting',
            name='observed_behavior',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='willing_to_contact',
            field=models.BooleanField(default=False),
        ),
    ]
