# Generated by Django 5.1.5 on 2025-03-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0009_missingperson_assigned_ngo_and_more'),
        ('sightings', '0004_sighting_companions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_persons.missingperson'),
        ),
    ]
