# Generated by Django 5.1.5 on 2025-03-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0009_missingperson_assigned_ngo_and_more'),
        ('sightings', '0005_alter_sighting_missing_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='crowd_density',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('VEHICLE', 'Vehicle'), ('PUBLIC_TRANSPORT', 'Public Transport'), ('OTHER', 'Other')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='missing_persons.missingperson'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='willing_to_contact',
            field=models.BooleanField(default=True),
        ),
    ]
