# Generated by Django 5.1.5 on 2025-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_alter_sighting_crowd_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='confidence_level_numeric',
            field=models.FloatField(default=0),
        ),
    ]
